### PR TITLE
Compatibility with blaze-builder-0.4.*

### PR DESCRIPTION
**Pull request by borsboom**
See also https://github.com/meiersi/blaze-builder-enumerator/issues/4, https://github.com/snapframework/snap-core/issues/227 and https://github.com/fpco/stackage/issues/442.

Figured I'd take a stab at it since I've done a few of these adaptations now and it's pretty-much become mechanical for me.

### CODE REVIEW

**Comment by meiersi** [comment]
Cool. Thank you very much for this work. I'll double-check the code on my desktop machine and release afterwards.

I think the dependency on streaming-commons is fine.

**Comment by snoyberg** [comment]
It would be great if this could make it into LTS 2. That would mean a release today. Is that possible? Pinging @gregorycollins as well, we'd need a snap version bump as well.

**Comment by meiersi** [comment]
Released: http://hackage.haskell.org/package/blaze-builder-enumerator-0.2.0.7

Thanks again to @manny-fp for the implementation and @snoyberg for the drive. Much appreciated!

**Comment by gregorycollins** [comment]
It's not building over here on 7.6.3:

```
Configuring blaze-builder-enumerator-0.2.0.7...
Building blaze-builder-enumerator-0.2.0.7...
Preprocessing library blaze-builder-enumerator-0.2.0.7...

Blaze/ByteString/Builder/Enumerator.hs:61:8:
    Could not find module `Data.ByteString.Builder.Extra'
    It is a member of the hidden package `bytestring-builder-0.10.4.1.2'.
    Perhaps you need to add `bytestring-builder' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```

**Pull request merged**
